/** Offline emoji catalogue with Russian and English keywords for search. */
export interface EmojiEntry {
  e: string;
  k: string;
}

export interface EmojiGroup {
  id: string;
  ru: string;
  en: string;
  items: EmojiEntry[];
}

const g = (id: string, ru: string, en: string, list: [string, string][]): EmojiGroup => ({
  id,
  ru,
  en,
  items: list.map(([e, k]) => ({ e, k })),
});

export const EMOJI_GROUPS: EmojiGroup[] = [
  g('work', 'Работа', 'Work', [
    ['🚀', 'rocket ракета запуск launch'],
    ['🎯', 'target цель goal мишень'],
    ['📌', 'pin булавка'],
    ['📍', 'pin location место'],
    ['🗺️', 'map карта roadmap'],
    ['🧭', 'compass компас направление'],
    ['📈', 'chart growth рост график'],
    ['📉', 'chart down падение'],
    ['📊', 'bar chart диаграмма аналитика'],
    ['🗂️', 'folders папки'],
    ['📁', 'folder папка'],
    ['📂', 'open folder папка'],
    ['🗃️', 'card box архив'],
    ['📋', 'clipboard планшет список'],
    ['📝', 'memo заметка note'],
    ['✏️', 'pencil карандаш'],
    ['🖊️', 'pen ручка'],
    ['📎', 'paperclip скрепка'],
    ['📐', 'ruler линейка'],
    ['📅', 'calendar календарь'],
    ['🗓️', 'calendar spiral календарь'],
    ['⏰', 'alarm будильник'],
    ['⏳', 'hourglass песочные часы срок'],
    ['⌛', 'hourglass done'],
    ['🧩', 'puzzle пазл'],
    ['🧪', 'test tube эксперимент experiment'],
    ['🔬', 'microscope исследование research'],
    ['🔭', 'telescope видение vision'],
    ['💡', 'idea идея lightbulb лампочка'],
    ['🧠', 'brain мозг'],
    ['🛠️', 'tools инструменты'],
    ['🔧', 'wrench ключ'],
    ['⚙️', 'gear шестеренка settings'],
    ['🧱', 'brick кирпич'],
    ['🏗️', 'construction стройка'],
    ['📦', 'package пакет релиз release'],
    ['🎁', 'gift подарок'],
    ['🏷️', 'label тег tag'],
    ['🔖', 'bookmark закладка'],
    ['📣', 'megaphone мегафон анонс'],
    ['📢', 'loudspeaker объявление'],
    ['💬', 'speech чат chat'],
    ['🗣️', 'speaking говорить'],
    ['🎙️', 'microphone микрофон встреча meeting'],
    ['🎧', 'headphones наушники'],
    ['📞', 'phone телефон звонок call'],
    ['✉️', 'envelope письмо email'],
    ['📬', 'mailbox почта'],
    ['💼', 'briefcase портфель бизнес'],
    ['🏢', 'office офис'],
    ['🏦', 'bank банк'],
    ['💰', 'money деньги бюджет budget'],
    ['💳', 'card карта оплата payment'],
    ['🧾', 'receipt чек'],
    ['⚖️', 'scale весы юрист legal'],
    ['🔒', 'lock замок безопасность security'],
    ['🔑', 'key ключ'],
    ['🛡️', 'shield щит защита'],
    ['🔗', 'link ссылка'],
    ['🧲', 'magnet магнит'],
  ]),
  g('symbols', 'Символы', 'Symbols', [
    ['✅', 'check done готово галочка'],
    ['☑️', 'checkbox чекбокс'],
    ['✔️', 'check галочка'],
    ['❌', 'cross крест нет'],
    ['⚠️', 'warning внимание риск risk'],
    ['🚨', 'alert сирена срочно urgent'],
    ['⛔', 'stop стоп'],
    ['🚧', 'construction в работе wip'],
    ['❓', 'question вопрос'],
    ['❗', 'exclamation важно'],
    ['⭐', 'star звезда'],
    ['🌟', 'glowing star звезда'],
    ['✨', 'sparkles блеск новое new'],
    ['⚡', 'lightning молния быстро fast'],
    ['🔥', 'fire огонь горит hot'],
    ['💎', 'gem алмаз'],
    ['🏆', 'trophy кубок победа'],
    ['🥇', 'medal медаль'],
    ['🎉', 'party праздник тада'],
    ['🎊', 'confetti конфетти'],
    ['❤️', 'heart сердце'],
    ['💚', 'green heart'],
    ['💙', 'blue heart'],
    ['💜', 'purple heart'],
    ['🧡', 'orange heart'],
    ['💛', 'yellow heart'],
    ['🖤', 'black heart'],
    ['🔴', 'red circle красный'],
    ['🟠', 'orange circle оранжевый'],
    ['🟡', 'yellow circle желтый'],
    ['🟢', 'green circle зеленый'],
    ['🔵', 'blue circle синий'],
    ['🟣', 'purple circle фиолетовый'],
    ['⚪', 'white circle белый'],
    ['⚫', 'black circle черный'],
    ['🟥', 'red square'],
    ['🟧', 'orange square'],
    ['🟨', 'yellow square'],
    ['🟩', 'green square'],
    ['🟦', 'blue square'],
    ['🟪', 'purple square'],
    ['🔶', 'diamond ромб'],
    ['🔷', 'blue diamond ромб'],
    ['♻️', 'recycle цикл'],
    ['🔄', 'refresh обновить sync'],
    ['➕', 'plus плюс'],
    ['💯', 'hundred сто'],
    ['🆕', 'new новое'],
    ['🆗', 'ok'],
    ['🔝', 'top топ'],
  ]),
  g('nature', 'Природа', 'Nature', [
    ['🌱', 'seedling росток старт'],
    ['🌿', 'herb трава'],
    ['🍀', 'clover клевер удача'],
    ['🌳', 'tree дерево'],
    ['🌲', 'evergreen ель'],
    ['🌵', 'cactus кактус'],
    ['🌸', 'blossom цветок'],
    ['🌻', 'sunflower подсолнух'],
    ['🌈', 'rainbow радуга'],
    ['☀️', 'sun солнце'],
    ['🌤️', 'sun cloud'],
    ['🌙', 'moon луна'],
    ['⭐', 'star'],
    ['🌊', 'wave волна'],
    ['🏔️', 'mountain гора'],
    ['🌋', 'volcano вулкан'],
    ['🌍', 'globe земля мир world'],
    ['🌐', 'globe сеть web'],
    ['🪐', 'planet планета'],
    ['☁️', 'cloud облако'],
    ['❄️', 'snowflake снежинка'],
    ['🐝', 'bee пчела'],
    ['🦋', 'butterfly бабочка'],
    ['🐙', 'octopus осьминог'],
    ['🦊', 'fox лиса'],
    ['🐻', 'bear медведь'],
    ['🦉', 'owl сова'],
    ['🐢', 'turtle черепаха'],
    ['🦄', 'unicorn единорог'],
    ['🐳', 'whale кит'],
  ]),
  g('objects', 'Предметы', 'Objects', [
    ['💻', 'laptop ноутбук'],
    ['🖥️', 'desktop компьютер'],
    ['📱', 'phone смартфон mobile'],
    ['⌨️', 'keyboard клавиатура'],
    ['🖱️', 'mouse мышь'],
    ['🤖', 'robot робот ai бот'],
    ['👾', 'alien игра game'],
    ['🎮', 'game геймпад'],
    ['🕹️', 'joystick'],
    ['📷', 'camera камера'],
    ['🎥', 'movie камера видео'],
    ['📺', 'tv телевизор'],
    ['🔋', 'battery батарея'],
    ['🔌', 'plug вилка интеграция'],
    ['💾', 'floppy сохранить'],
    ['🧮', 'abacus счеты'],
    ['📚', 'books книги'],
    ['📖', 'book книга'],
    ['📓', 'notebook блокнот'],
    ['📰', 'newspaper газета'],
    ['🎨', 'palette палитра дизайн design'],
    ['🖌️', 'brush кисть'],
    ['✂️', 'scissors ножницы'],
    ['🧵', 'thread нить'],
    ['🔔', 'bell колокол уведомление'],
    ['🎵', 'music музыка'],
    ['🏠', 'house дом'],
    ['🏡', 'home дом сад'],
    ['🚗', 'car машина'],
    ['✈️', 'plane самолет'],
    ['🚢', 'ship корабль'],
    ['🚂', 'train поезд'],
    ['🚲', 'bike велосипед'],
    ['⛵', 'sailboat парусник'],
    ['🛸', 'ufo'],
    ['⚓', 'anchor якорь'],
    ['🎈', 'balloon шар'],
    ['🪄', 'magic wand палочка'],
    ['🔮', 'crystal ball прогноз'],
    ['🧿', 'nazar'],
  ]),
  g('people', 'Люди', 'People', [
    ['😀', 'smile улыбка'],
    ['😎', 'cool круто'],
    ['🤓', 'nerd'],
    ['🤔', 'thinking думаю'],
    ['🧐', 'monocle исследую'],
    ['😅', 'sweat'],
    ['🥳', 'party праздник'],
    ['🤯', 'mind blown взрыв мозга'],
    ['😴', 'sleep сон'],
    ['🙌', 'raised hands ура'],
    ['👏', 'clap аплодисменты'],
    ['👍', 'thumbs up класс'],
    ['👋', 'wave привет'],
    ['🤝', 'handshake рукопожатие партнер'],
    ['💪', 'muscle сила'],
    ['🙏', 'pray спасибо'],
    ['👀', 'eyes смотреть'],
    ['👤', 'user пользователь'],
    ['👥', 'users команда team'],
    ['🧑‍💻', 'developer разработчик'],
    ['👩‍💼', 'manager менеджер'],
    ['🧑‍🎨', 'designer дизайнер'],
    ['🧑‍🔬', 'scientist исследователь'],
    ['🦸', 'superhero герой'],
    ['🧙', 'wizard маг'],
  ]),
  g('food', 'Еда', 'Food', [
    ['☕', 'coffee кофе'],
    ['🍵', 'tea чай'],
    ['🍕', 'pizza пицца'],
    ['🍔', 'burger бургер'],
    ['🍩', 'donut пончик'],
    ['🍪', 'cookie печенье'],
    ['🍎', 'apple яблоко'],
    ['🍋', 'lemon лимон'],
    ['🍉', 'watermelon арбуз'],
    ['🥑', 'avocado авокадо'],
    ['🌶️', 'pepper перец'],
    ['🍿', 'popcorn попкорн'],
    ['🎂', 'cake торт'],
    ['🍰', 'cake пирог'],
    ['🥐', 'croissant круассан'],
  ]),
];

export const ALL_EMOJI: EmojiEntry[] = EMOJI_GROUPS.flatMap((grp) => grp.items);
