import { expect, test } from '@playwright/test';

test('welcome, registration draft, durable account, project and viewer access', async ({ page, browser }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', (e) => errors.push(e.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Добро пожаловать в Done' })).toBeVisible();
  await expect(page.getByRole('img', { name: 'Done', exact: true })).toHaveCount(1);
  await expect(page.getByRole('img', { name: 'Done', exact: true })).toHaveCSS('opacity', '1');
  await expect(page.getByRole('heading', { name: 'Добро пожаловать в Done' }).locator('..')).toHaveCSS('opacity', '1');
  await page.screenshot({ path: testInfo.outputPath('welcome.png'), animations: 'disabled' });
  await page.getByRole('button', { name: 'Начать', exact: true }).click();
  await page.getByLabel('Имя', { exact: true }).fill('Мария');
  await page.getByLabel('Название пространства').fill('Команда QA');
  await page.getByLabel('Email', { exact: true }).fill('owner@example.test');
  await page.getByRole('button', { name: 'Назад', exact: true }).click();
  await page.reload();
  await page.getByRole('button', { name: 'Начать', exact: true }).click();
  await expect(page.getByLabel('Имя', { exact: true })).toHaveValue('Мария');
  await expect(page.getByLabel('Название пространства')).toHaveValue('Команда QA');
  await expect(page.getByLabel('Email', { exact: true })).toHaveValue('owner@example.test');
  await page.getByLabel('Пароль', { exact: true }).fill('Disposable-QA-Password-2026');
  await page.getByRole('button', { name: 'Создать аккаунт', exact: true }).click();
  await expect(page.getByRole('heading', { name: /Мария/ })).toBeVisible();
  await page.getByRole('main').getByRole('button', { name: 'Новый проект', exact: true }).click();
  await page.getByPlaceholder('Новый проект', { exact: true }).fill('Запуск продукта');
  const savedProject = page.waitForResponse((r) => r.url().endsWith('/api/workspace') && r.request().method() === 'PUT' && r.status() === 200);
  await page.getByPlaceholder('Новый проект', { exact: true }).press('Tab');
  await savedProject;
  await page.reload();
  await expect(page.getByPlaceholder('Новый проект', { exact: true })).toHaveValue('Запуск продукта');
  await page.keyboard.press('c');
  await page.getByPlaceholder('Что нужно сделать?').fill('Проверить сохранение');
  const savedTask = page.waitForResponse((r) => r.url().endsWith('/api/workspace') && r.request().method() === 'PUT' && r.status() === 200);
  await page.getByPlaceholder('Что нужно сделать?').press('Enter');
  await savedTask;
  await page.getByRole('link', { name: 'Мои задачи', exact: true }).click();
  await page.getByRole('button', { name: 'Вся команда', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Проверить сохранение', exact: true })).toBeVisible();

  await page.getByRole('link', { name: 'Люди и доступ', exact: true }).click();
  await page.getByRole('button', { name: 'Пригласить', exact: true }).click();
  await page.getByLabel('Email', { exact: true }).fill('viewer@example.test');
  await page.getByLabel('Роль', { exact: true }).selectOption('viewer');
  await page.getByRole('button', { name: 'Создать приглашение' }).click();
  const invitation = await page.getByLabel('Ссылка приглашения').inputValue();
  await page.getByRole('button', { name: 'Готово', exact: true }).click();
  await expect(page.locator('.anim-overlay')).toHaveCount(0);
  await expect(page.getByRole('status')).toHaveCount(0, { timeout: 10000 });
  await page.screenshot({ path: testInfo.outputPath('admin.png'), animations: 'disabled' });

  const viewerContext = await browser.newContext({ locale: 'ru-RU' });
  const viewer = await viewerContext.newPage();
  await viewer.goto(invitation);
  await viewer.getByLabel('Имя', { exact: true }).fill('Наблюдатель QA');
  await viewer.getByLabel('Пароль', { exact: true }).fill('Disposable-QA-Viewer-2026');
  await viewer.getByRole('button', { name: 'Создать аккаунт', exact: true }).click();
  await expect(viewer.getByText('Режим просмотра', { exact: false })).toBeVisible();
  await expect(viewer.getByRole('link', { name: 'Люди и доступ', exact: true })).toHaveCount(0);
  await viewer.goto('/admin');
  await expect(viewer.getByRole('heading', { name: 'Доступ только администраторам' })).toBeVisible();
  const denied = await viewer.request.put('/api/workspace', { headers: { 'x-done-client': 'web' }, data: { revision: 0, data: {} } });
  expect(denied.status()).toBe(403);
  await viewerContext.close();

  await page.getByRole('button', { name: 'Выйти', exact: true }).click();
  await page.getByRole('button', { name: 'Уже есть аккаунт? Войти', exact: true }).click();
  await page.getByLabel('Email', { exact: true }).fill('owner@example.test');
  await page.getByLabel('Пароль', { exact: true }).fill('Disposable-QA-Password-2026');
  await page.getByRole('button', { name: 'Войти', exact: true }).click();
  await page.getByRole('link', { name: 'Мои задачи', exact: true }).click();
  await page.getByRole('button', { name: 'Вся команда', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Проверить сохранение', exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});
